Bootcamp/projects/travel_site/config/routes.rb
Rails.application.routes.draw do
  resources :cities

  root 'cities#index', as: 'cities_index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Bootcamp/projects/travel_site/app/models/city.rb
class City < ApplicationRecord
end

Bootcamp/projects/travel_site/app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: [:show, :edit, :update, :destroy]

  # GET /cities
  # GET /cities.json
  def index
    @cities = City.order(:state)
  end

  # GET /cities/1
  # GET /cities/1.json
  def show
  end

  # GET /cities/new
  def new
    @city = City.new
  end

  # GET /cities/1/edit
  def edit
  end

  # POST /cities
  # POST /cities.json
  def create
    @city = City.new(city_params)

    respond_to do |format|
      if @city.save
        format.html { redirect_to @city, notice: 'City was successfully created.' }
        format.json { render :show, status: :created, location: @city }
      else
        format.html { render :new }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cities/1
  # PATCH/PUT /cities/1.json
  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to @city, notice: 'City was successfully updated.' }
        format.json { render :show, status: :ok, location: @city }
      else
        format.html { render :edit }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1
  # DELETE /cities/1.json
  def destroy
    @city.destroy
    respond_to do |format|
      format.html { redirect_to cities_url, notice: 'City was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city
      @city = City.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def city_params
      params.require(:city).permit(:name, :state, :region, :description)
    end
end

Bootcamp/projects/travel_site/app/helpers/cities_helper.rb
module CitiesHelper
end

Bootcamp/projects/travel_site/app/views/cities/_form.html.erb
<%= form_for(city) do |f| %>
  <% if city.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(city.errors.count, "error") %> prohibited this city from being saved:</h2>

      <ul>
      <% city.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>

  <div class="field">
    <%= f.label :region %>
    <%= f.text_field :region %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Bootcamp/projects/travel_site/app/views/cities/edit.html.erb
<h1>Editing City</h1>

<%= render 'form', city: @city %>

<%= link_to 'Show', @city %> |
<%= link_to 'Back', cities_path %>

Bootcamp/projects/travel_site/app/views/cities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cities</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>State</th>
      <th>Region</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cities.each do |city| %>
      <tr>
        <td><%= city.name %></td>
        <td><%= city.state %></td>
        <td><%= city.region %></td>
        <td><%= sanitize(city.description) %></td>
        <td><%= link_to 'Show', city %></td>
        <td><%= link_to 'Edit', edit_city_path(city) %></td>
        <td><%= link_to 'Destroy', city, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New City', new_city_path %>

Bootcamp/projects/travel_site/app/views/cities/new.html.erb
<h1>New City</h1>

<%= render 'form', city: @city %>

<%= link_to 'Back', cities_path %>

Bootcamp/projects/travel_site/app/views/cities/show.html.erb
<div class='main'>
  <p id="notice"><%= notice %></p>

  <h2><%= @city.name %></h2>
  
  <iframe width="600" height="450" frameborder="0" style="border:0" src="https://www.google.com/maps/embed/v1/place?q=place_id:ChIJP9A_FgiHBDkRzXZQvg6oKYE&key=AIzaSyCJDSSvbe4lz8h-ZWW6bYxQGkJBD6N5ltE" allowfullscreen></iframe>

  <p>
    <strong>State:</strong>
    <%= @city.state %>
  </p>

  <p>
    <strong>Region:</strong>
    <%= @city.region %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @city.description %>
  </p>

  <%= link_to 'Edit', edit_city_path(@city) %> |
  <%= link_to 'Back', cities_path %>
</div>

Bootcamp/projects/travel_site/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TravelSite</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>